# shellcheck shell=bash
MODEL_KIND="embedding"
HOST="${HOST:-0.0.0.0}"
THREADS="${THREADS:-$(sysctl -n hw.ncpu)}"
CTX_SIZE="${CTX_SIZE:-1024}"
GPU_LAYERS="${GPU_LAYERS:-99}"
BATCH_SIZE="${BATCH_SIZE:-1024}"
UBATCH_SIZE="${UBATCH_SIZE:-512}"
POOLING="${POOLING:-mean}"
